services:
  user-service:
    build:
      context: ./services/user-service
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - expense-tracker-network
    depends_on:
      - kafka

  transaction-service:
    build:
      context: ./services/transaction-service
    ports:
      - "8081:8081"
    env_file:
      - .env
    networks:
      - expense-tracker-network
    depends_on:
      - kafka

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - expense-tracker-network
    env_file:
      - .env

  kafka:
    image: confluentinc/cp-kafka:latest
    networks:
      - expense-tracker-network
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    env_file:
      - .env

networks:
  expense-tracker-network:
    driver: bridge

