version: '3.8'

services:
  user-service:
    build:
      context: ./services/user-service
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - expense-tracker-network
    depends_on:
      - kafka

  transaction-service:
    build:
      context: ./services/transaction-service
    ports:
      - "8081:8081"
    env_file:
      - .env
    networks:
      - expense-tracker-network
    depends_on:
      - kafka

  budgeting-service:
    build:
      context: ./services/budgeting-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    env_file:
      - .env
    networks:
      - expense-tracker-network
    depends_on:
      - kafka

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0  # Specific version
    networks:
      - expense-tracker-network
    env_file:
      - .env

  kafka:
    image: confluentinc/cp-kafka:7.4.0  # Changed from :latest to :7.4.0
    networks:
      - expense-tracker-network
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    env_file:
      - .env

networks:
  expense-tracker-network:
    driver: bridge

