version: '3.8'

# Defines the services (containers) that make up your app
services:
  # This is the service definition for your user-service
  user-service:
    build:
      # Tells Docker Compose to build the image from the Dockerfile
      # located in the ./services/user-service directory
      context: ./services/user-service
    ports:
      # Maps port 8080 on your host machine to port 8080 in the container
      - "8080:8080"

    # This is the key section for your question.
    # It defines the environment variables that will be available
    # inside the user-service container.
    environment:
      # Spring Boot will automatically pick up these variables because of the
      # placeholders like ${SPRING_DATASOURCE_URL} in your application.properties
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ep-holy-bush-adell94i-pooler.c-2.us-east-1.aws.neon.tech:5432/neondb?sslmode=require&channel_binding=require
      - SPRING_DATASOURCE_USERNAME=neondb_owner
      - SPRING_DATASOURCE_PASSWORD=npg_idLfOP1Y5sna
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    networks:
      # Connects this service to a shared network
      - expense-tracker-net

# Defines the network that allows containers to communicate with each other
networks:
  expense-tracker-net:
    driver: bridge

